{
  "flags":  256,
  "name":  "Completion",
  "kind":  "SPAN_KIND_INTERNAL",
  "attributes":  [
    {
      "key":  "llm.system",
      "value":  {
        "stringValue":  "openai"
      }
    },
    {
      "key":  "input.value",
      "value":  {
        "stringValue":  "{\"model\": \"babbage-002-wrong\", \"prompt\": \"def fib(n):\\n    if n <= 1:\\n        return n\\n    else:\\n        return fib(n-1) + fib(n-2)\"}"
      }
    },
    {
      "key":  "input.mime_type",
      "value":  {
        "stringValue":  "application/json"
      }
    },
    {
      "key":  "llm.invocation_parameters",
      "value":  {
        "stringValue":  "{\"model\": \"babbage-002-wrong\"}"
      }
    },
    {
      "key":  "llm.prompts.0.prompt.text",
      "value":  {
        "stringValue":  "def fib(n):\n    if n <= 1:\n        return n\n    else:\n        return fib(n-1) + fib(n-2)"
      }
    },
    {
      "key":  "openinference.span.kind",
      "value":  {
        "stringValue":  "LLM"
      }
    }
  ],
  "events":  [
    {
      "name":  "exception",
      "attributes":  [
        {
          "key":  "exception.type",
          "value":  {
            "stringValue":  "openai.NotFoundError"
          }
        },
        {
          "key":  "exception.message",
          "value":  {
            "stringValue":  "Error code: 404 - {'error': {'message': 'The model `babbage-002-wrong` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}"
          }
        },
        {
          "key":  "exception.stacktrace",
          "value":  {
            "stringValue":  "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.13/site-packages/openinference/instrumentation/openai/_request.py\", line 391, in __call__\n    response = await wrapped(*args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/openai/_base_client.py\", line 1594, in request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `babbage-002-wrong` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}\n"
          }
        },
        {
          "key":  "exception.escaped",
          "value":  {
            "stringValue":  "False"
          }
        }
      ]
    }
  ],
  "status":  {
    "message":  "NotFoundError: Error code: 404 - {'error': {'message': 'The model `babbage-002-wrong` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}",
    "code":  "STATUS_CODE_ERROR"
  }
}
